# Generated by Django 4.2.2 on 2024-07-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_blok_users', 'Может заблокировать пользователя'), ('can_see_users', 'Может посмотреть список пользователей')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
