# Generated by Django 4.2.2 on 2024-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Изображение')),
                ('date_create', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('publication_sign', models.BooleanField(default=False, verbose_name='Признак публикации')),
                ('views_counter', models.PositiveIntegerField(default=0, help_text='Количество просмотров', verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
            },
        ),
    ]
