# Generated by Django 5.0.7 on 2024-07-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_clients_mailings_сhance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.CharField(choices=[('создано', 'Создано'), ('начато', 'Начато'), ('завершено', 'Завершено')], max_length=100, verbose_name='Статус'),
        ),
    ]
