# Generated by Django 5.0.7 on 2024-07-15 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='e',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время окончания рассылки'),
            preserve_default=False,
        ),
    ]
