# Generated by Django 4.2.2 on 2024-07-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailings_message_alter_mailings_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailings',
            name='message',
        ),
        migrations.AddField(
            model_name='messages',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailings.mailings'),
        ),
    ]
