# Generated by Django 4.2.2 on 2024-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_remove_messages_mailing_mailings_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
    ]
