# Generated by Django 4.2.2 on 2024-07-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_mailings_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'permissions': [('can_unplug_mailings', 'Может отключить рассылку')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
